import { Response, Request } from 'express';
import { AuthRequest } from '../middlewares/authMiddleware';
import { supabase } from '../config/supabase';
import { submitOrder, getTransactionStatus } from '../utils/pesapal';

const APP_FRONTEND_URL = process.env.APP_FRONTEND_URL || 'https://afya-links-frontend.vercel.app'; // Replace with actual app redirect scheme or deep link

export const initiatePayment = async (req: AuthRequest, res: Response): Promise<void> => {
    try {
        const clinicId = req.user?.id;
        const { order_id } = req.body;

        if (!order_id) {
            res.status(400).json({ success: false, message: 'order_id is required' });
            return;
        }

        // Check order details
        const { data: order, error: orderError } = await supabase
            .from('orders')
            .select('*, clinic:users!orders_clinic_id_fkey(name, phone, email)')
            .eq('id', order_id)
            .eq('clinic_id', clinicId)
            .single();

        if (orderError || !order) {
            res.status(404).json({ success: false, message: 'Order not found' });
            return;
        }

        if (order.status !== 'AWAITING_PAYMENT') {
            res.status(400).json({ success: false, message: 'Order is not awaiting payment' });
            return;
        }

        // Prepare Pesapal order
        const clinicUser = Array.isArray(order.clinic) ? order.clinic[0] : order.clinic;

        const pesapalResponse = await submitOrder({
            id: order.id,
            amount: order.total_payable,
            description: `Afya Links Order ${order.id}`,
            callback_url: `${APP_FRONTEND_URL}/payment-callback?order_id=${order.id}`,
            billing_address: {
                email_address: clinicUser?.email || 'test@pesapal.com',
                phone_number: clinicUser?.phone || '0700000000',
                country_code: 'UG',
                first_name: clinicUser?.name?.split(' ')[0] || 'Clinic',
                last_name: clinicUser?.name?.split(' ')[1] || 'Owner'
            }
        });

        // The pesapal tracking ID could be saved here, but it's normally generated by Pesapal and passed back in IPN. 
        // We'll log it if needed, or simply let the IPN handle it. We can insert a pending transaction log:
        await supabase.from('pesapal_transactions').insert([{
            order_id: order.id,
            tracking_id: pesapalResponse.order_tracking_id,
            merchant_reference: order.id,
            amount: order.total_payable,
            payment_status_description: 'PENDING'
        }]);

        res.status(200).json({
            success: true,
            redirect_url: pesapalResponse.redirect_url,
            order_tracking_id: pesapalResponse.order_tracking_id
        });

    } catch (error: any) {
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * Pesapal Webhook (IPN)
 * This is called by Pesapal when a payment succeeds or fails.
 */
export const pesapalWebhook = async (req: Request, res: Response): Promise<void> => {
    try {
        const { OrderTrackingId, OrderNotificationType, OrderMerchantReference } = req.query;

        if (!OrderTrackingId) {
            res.status(400).json({ success: false, message: 'Missing OrderTrackingId' });
            return;
        }

        // Query status from Pesapal
        const txStatus = await getTransactionStatus(OrderTrackingId as string);

        // txStatus example: { amount, payment_status_code, payment_status_description }
        const isCompleted = txStatus.payment_status_code === 1; // 1 = COMPLETED in Pesapal V3 usually
        const isFailed = txStatus.payment_status_code === 2 || txStatus.payment_status_code === 3; // 2=FAILED, 3=REVERSED

        // Update transaction log
        await supabase
            .from('pesapal_transactions')
            .upsert({
                tracking_id: OrderTrackingId as string,
                order_id: OrderMerchantReference as string,
                merchant_reference: OrderMerchantReference as string,
                amount: txStatus.amount,
                currency: txStatus.currency,
                payment_method: txStatus.payment_method,
                payment_status_code: txStatus.payment_status_code,
                payment_status_description: txStatus.payment_status_description,
                ipn_notified: true
            }, { onConflict: 'tracking_id' });

        // If completed, update order and escrow status
        if (isCompleted) {
            // ONLY execute if status is AWAITING_PAYMENT to prevent double-funding
            const { data: order } = await supabase
                .from('orders')
                .select('status, total_payable')
                .eq('id', OrderMerchantReference)
                .single();

            if (order && order.status === 'AWAITING_PAYMENT') {
                if (Number(order.total_payable) === Number(txStatus.amount)) {
                    // Correct payment — update order
                    await supabase.from('orders')
                        .update({
                            status: 'PAID',
                            payment_status: 'VERIFIED'
                        })
                        .eq('id', OrderMerchantReference);

                    // Fetch clinic_id and pharmacy_id for notifications
                    const { data: fullOrder } = await supabase
                        .from('orders')
                        .select('clinic_id, pharmacy_id')
                        .eq('id', OrderMerchantReference)
                        .single();

                    if (fullOrder) {
                        const shortId = (OrderMerchantReference as string).slice(0, 8).toUpperCase();
                        Promise.resolve(supabase.from('notifications').insert([
                            {
                                user_id: fullOrder.clinic_id,
                                title: '✅ Payment Confirmed',
                                body: `Your payment for order #${shortId} was successful. The pharmacy is now processing your order.`,
                                type: 'PAYMENT_SUCCESS',
                                is_read: false
                            },
                            {
                                user_id: fullOrder.pharmacy_id,
                                title: '💰 Payment Received – Action Required',
                                body: `Payment for order #${shortId} has been confirmed. Please check your Orders Inbox and action this order.`,
                                type: 'PAYMENT_SUCCESS',
                                is_read: false
                            }
                        ])).catch(console.error);
                    }
                } else {
                    // Amount mismatch
                    console.error(`Amount mismatch on order ${OrderMerchantReference}. Expected ${order.total_payable}, got ${txStatus.amount}`);
                }
            }
        } else if (isFailed) {
            await supabase.from('orders')
                .update({ payment_status: 'PAYMENT_FAILED' })
                .eq('id', OrderMerchantReference);
        }

        // Important: Respond to Pesapal with 200 OK
        res.status(200).json({
            OrderTrackingId,
            OrderNotificationType,
            OrderMerchantReference,
            status: 200
        });

    } catch (error: any) {
        console.error('Pesapal Webhook Error:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};
